// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookingConfirmationController from "./booking_confirmation_controller"
application.register("booking-confirmation", BookingConfirmationController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ConversationTriggerController from "./conversation_trigger_controller"
application.register("conversation-trigger", ConversationTriggerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationSubscriptionController from "./notification_subscription_controller"
application.register("notification-subscription", NotificationSubscriptionController)
